#ifndef NETWORKINFO_GLOBAL_H
#define NETWORKINFO_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(NETWORKINFO_LIBRARY)
#  define NETWORKINFOSHARED_EXPORT Q_DECL_EXPORT
#else
#  define NETWORKINFOSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // NETWORKINFO_GLOBAL_H
