/*!
 * Config file for videoplayer.
 */

var SCALE_RATIO = 1//1.5;//2/3;

//screen size
var ORIGINAL_SCREEN_WIDTH = 720*SCALE_RATIO
var ORIGINAL_SCREEN_HEIGHT = 1080*SCALE_RATIO

//Font
var FONT_SIZE_LARGE = 36*SCALE_RATIO;
var FONT_SIZE_32 = 32*SCALE_RATIO;
var FONT_SIZE_26 = 26*SCALE_RATIO;
// Status bar
var STATUS_BAR_HEIGHT = 48*SCALE_RATIO;

// Video filter
var VIDEOS_FILTER_HEIGHT = 255*SCALE_RATIO
var VIDEOS_FILTER_SPACING = 10*SCALE_RATIO
var VIDEOS_LISTVIEW_WIDTH = (720 - 80)*SCALE_RATIO
var VIDEOS_LIST_ELEMENT_HEIGHT = 100*SCALE_RATIO
var VIDEOS_LISTVIEW_UNUSEFUL_WIDTH = 40*SCALE_RATIO
var VIDEOS_LISTVIEW_UNUSEFUL_BOTTOM_HEIGHT = 45*SCALE_RATIO

// Video thumbnails
var THUMBNAIL_NAME_SIZE = 20*SCALE_RATIO
var THUMBNAIL_NAME_LEFT_MARGIN = 15*SCALE_RATIO
var THUMBNAIL_NAME_BOTTOM_MARGIN = 12*SCALE_RATIO
var THUMBNAIL_TIME_SIZE = 18*SCALE_RATIO
var THUMBNAIL_TIME_RIGHT_MARGIN = 15*SCALE_RATIO
var THUMBNAIL_TIME_BOTTOM_MARGIN = 15*SCALE_RATIO
var THUMBNAIL_SELECTED_SIZE = 50*SCALE_RATIO
var THUMBNAIL_SELECTED_RIGHT_MARGIN = 10*SCALE_RATIO
var THUMBNAIL_SELECTED_BOTTOM_MARGIN = 10*SCALE_RATIO

// Video operation
var VIDEO_OPERATION_SPACING = 60*SCALE_RATIO //TODO: need to ask

// Play controls
var CONTROL_HEIGHT = 190*SCALE_RATIO
var CONTROL_HEIGHT_PORT = 280*SCALE_RATIO
var CONTROL_PROGRESS_BAR_HEIGHT = 10*SCALE_RATIO
var CONTROL_PROGRESS_CURSOR = 35*SCALE_RATIO

var CONTROL_CURRENTTIME_LEFT_MARGIN = 20*SCALE_RATIO
var CONTROL_CURRENTTIME_TOP_MARGIN = 5*SCALE_RATIO
var CONTROL_CURRENTTIME_COLOR = "#1ca72b"

var CONTROL_DURATION_RIGHT_MARGIN = 20*SCALE_RATIO
var CONTROL_DURATION_TOP_MARGIN = 5*SCALE_RATIO
var CONTROL_DURATION_COLOR = "#787777"
var CONTROL_TEXT_SIZE = 22*SCALE_RATIO

var CONTROL_BUTTON_AREA_HEIGHT = 88*SCALE_RATIO
var CONTROL_BUTTON_TOP_MARGIN = 5*SCALE_RATIO
var CONTROL_BUTTON_BOTTOM_MARGIN = 10*SCALE_RATIO
var CONTROL_BUTTON_SPACING = 78*SCALE_RATIO
var CONTROL_BUTTON_HEIGHT=110*SCALE_RATIO

// Playing list view
var PLAYING_LIST_WIDTH = 280*SCALE_RATIO
var PLAYING_LIST_TOP_MARGIN = 20*SCALE_RATIO
var PLAYING_LIST_BOTTOM_MARGIN = 20*SCALE_RATIO
var PLAYING_LIST_LEFT_MARGIN = 20*SCALE_RATIO
var PLAYING_LIST_RIGHT_MARGIN = 20*SCALE_RATIO
var PLAYING_LIST_SPACING = 20*SCALE_RATIO
var PLAYING_LIST_VIEW_WIDTH = (276-40)*SCALE_RATIO
var PLAYING_LIST_FILE_NAME_SIZE = 18*SCALE_RATIO
var PLAYING_LIST_FILE_NAME_LEFT_MARGIN = 15*SCALE_RATIO
var PLAYING_LIST_FILE_NAME_BOTTOM_MARGIN = 15*SCALE_RATIO
var PLAYING_LIST_FILE_TIME_SIZE = 20*SCALE_RATIO //TODO: need to ask
var PLAYING_LIST_FILE_TIME_LEFT_MARGIN = 15*SCALE_RATIO
var PLAYING_LIST_FILE_TIME_BOTTOM_MARGIN = 15*SCALE_RATIO

var PLAYING_LIST_EXPAND_WIDTH = 63*SCALE_RATIO
var PLAYING_LIST_EXPAND_HIGHT = 126*SCALE_RATIO
var PLAYING_LIST_EXPAND_HOT_AREA = 43*SCALE_RATIO

var PLAYER_FLOAT_BG = "#232323"

// History list view
var HISTORY_CELL_HEIGHT = 160*SCALE_RATIO
var HISTORY_CELL_PHOTO_HEIGHT = 140 * SCALE_RATIO
var HISTORY_FILENAME_WIDTH = 330*SCALE_RATIO
